<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="Cricket.css"?>

<!DOCTYPE Sports[
<!ELEMENT Sports (Cricket+)>
<!ELEMENT Cricket (name,hundreds,fifties)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT hundreds (#PCDATA)>
<!ELEMENT fifties (#PCDATA)>
]>

<Sports>
 <Cricket>
   <name>Virat Kohli</name>	
   <hundreds>75</hundreds>
   <fifties>130</fifties>
 </Cricket>
 
 <Cricket>
  <name>Rohit Sharma</name>	
   <hundreds>75</hundreds>
   <fifties>150</fifties>
 </Cricket>
 
 <Cricket>
  <name>Suryakumar Yadav</name>	
   <hundreds>65</hundreds>
   <fifties>120</fifties>
 </Cricket>
 
 <Cricket>
  <name>Kunal Pandya</name>	
   <hundreds>60</hundreds>
   <fifties>55</fifties>
 </Cricket>
 
 <Cricket>
  <name>Hardik Pandya</name>	
   <hundreds>30</hundreds>
   <fifties>50</fifties>
 </Cricket>
</Sports>

	 

