<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="cricket.css"?>

<!DOCTYPE Sports[
<!ELEMENT Sports (Cricket+)>
<!ELEMENT Cricket (name,hundreds,fifties)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT hundreds (#PCDATA)>
<!ELEMENT fifties (#PCDATA)>
]>

<Sports>
<Cricket>
<name>Virat Kohli</name>
<hundreds>75</hundreds>
<fifties>130</fifties>
</Cricket>

<Cricket>
<name>Joe Root</name>
<hundreds>46</hundreds>
<fifties>108</fifties>
</Cricket>
</Sports>